spring:
  application:
    name: emulator
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  liquibase:
    change-log: db/changelog/main-changelog.xml
server:
  port: 8081
